name: arquicart
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.31
  permission_handler: ^5.0.1+1
  flutter_auth_buttons: ^0.9.0
  provider: ^4.3.2+1
  geolocator: ^6.0.0+2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/